/// A deliberate indirection so widely-imported app code (permissions_prompt.dart,
/// chats_list_screen.dart, auth_controller.dart — all reachable from many unit
/// tests) can trigger starting/stopping live-location background reporting
/// without importing `location_service.dart` itself.
///
/// That file is genuinely uncompilable outside a real `flutter build`/`flutter
/// run` targeting `lib/main.dart`: its background-isolate entrypoints call
/// `DartPluginRegistrant.ensureInitialized()` (flutter_background_service's own
/// documented, required pattern for registering plugins in that headless
/// isolate), and that symbol is generated by Flutter's build tooling
/// (`.dart_tool/flutter_build/dart_plugin_registrant.dart`) and woven in only for
/// the actual app target — `flutter test`/`flutter analyze` resolve a different
/// target and hit a real "Undefined name" compile error the moment anything they
/// touch imports that file, even transitively. `main.dart` (never imported by any
/// test — confirmed by grepping test/ for it) is the one place that really does
/// import `location_service.dart` and wires these hooks to the real
/// implementation; everything else goes through this file instead.
library;

typedef AsyncVoidCallback = Future<void> Function();

Future<void> _noop() async {}

class LocationServiceHooks {
  LocationServiceHooks._();

  /// Replaced with `LocationService.ensureStarted` by main.dart at startup.
  /// Defaults to a no-op so a call site (or a test) that runs before that
  /// wiring — or in a test process, which never runs main.dart at all — is
  /// harmless rather than a null-check crash.
  static AsyncVoidCallback ensureStarted = _noop;
  static AsyncVoidCallback stop = _noop;
}
